pandoranohako/freemarket_sample_65e

- app/assets/stylesheets/mypage.scss
- app/views/mypage/index.html.haml
FacebookとGoogleのリンクは後でやります。（CSSも同様）
> [WIP]ログイン画面1

- app/assets/stylesheets/_mypage-sidebar.scss
- app/assets/stylesheets/application.scss
- app/views/mypage/_mypage-sidebar.html.haml
- app/views/mypage/index.html.haml
#What
　マイページのサイドバーを作成しました。
#Why
　サイドバーはメルカリクローンのマイページに使う根幹機能であるため。
> add mypage-sidebar

- README.md
- app/models/product.rb
- db/migrate/20191229044350_create_products.rb
- spec/models/product_spec.rb
productモデルの作成と、マイグレーションファイルの編集。
商品のデータが入るテーブルを作成するための準備のため。
商品が関係するサーバーサイド開発に入る準備のため。
> Productモデルとマイグレーションファイルの作成

- db/schema.rb
> productsテーブルの作成

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/index.scss
- app/assets/stylesheets/modules/_new_product.scss
- app/controllers/products_controller.rb
- app/views/products/new.html.haml
- app/views/shared/_display_btn.html.haml
- config/routes.rb
商品出品ページのルーティングを作成する。
商品出品ページ用のhaml, scssファイルを作成する。
【サーバーサイド】商品出品の開発が本格的に始まる前に、商品出品ページの見た目を整えるため。
> 【WIP】【マークアップ】商品出品ページ

- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/sns_credential.rb
- app/models/user.rb
- app/views/devise/registrations/index.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20200109082800_create_sns_credentials.rb
- db/schema.rb
- spec/factories/sns_credentials.rb
- spec/models/sns_credential_spec.rb
- OmniAuthを使用してregisterコントローラーを修正
- SNSアカウントのテーブルを作成
- userモデルの修正
- 新規登録入口ページの修正
- デバイス配下のルーティングを修正
新規登録機能でsnsのアカウントでも登録できるよう実装
> 【WIP】【サーバサイド】ユーザー新規登録機能、ログイン(SNS認証)

- app/assets/stylesheets/address.scss
- app/assets/stylesheets/index.scss
- app/assets/stylesheets/new.scss
- app/views/devise/registrations/index.html.haml
- app/views/devise/registrations/new.html.haml
> 【WIP】【フロントサイド】新規登録ページのビュー調整

- app/assets/stylesheets/_mypage-sidebar.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_mypage.scss
- app/assets/stylesheets/modules/_profile.scss
- app/views/mypage/index.html.haml
- db/schema.rb
mypage配下にindex.htmlを作成
本ブランチにて、作業後にタブ切り替え機能を実装。
アプリログアウトやプロフィール編集ページへの入り口となるマイページを用意するため。
> 【WIP】【フロントサイド】ユーザーマイページ作成

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/index.scss
- app/assets/stylesheets/modules/_signin.scss
- app/assets/stylesheets/modules/_top_page_header.scss
- app/views/devise/registrations/new_address.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/shared/_top_page_header.html.haml
ユーザー新規登録・ログイン機能周りの不足分と調整
ユーザー新規登録・ログイン機能を仕上げるため
> 【WIP】ユーザー新規登録機能とフロントの不足分対応と調整

- app/assets/stylesheets/modules/_mypage.scss
- app/controllers/users/registrations_controller.rb
- app/models/address.rb
- app/models/user.rb
- app/views/devise/sessions/logout.html.haml
- app/views/mypage/_mypage-sidebar.html.haml
- config/routes.rb
- ログアウトのためにdestroyアクションを作成
- ルーティング設定
- ログアウトページを作成する
ログアウト機能を実装するため
> 【WIP】【マークアップ】ユーザーログアウトページ

- app/assets/stylesheets/address.scss
- app/assets/stylesheets/modules/_mypage.scss
- app/controllers/mypage_controller.rb
- app/views/mypage/_mypage-sidebar.html.haml
- app/views/mypage/identification.html.haml
- config/breadcrumbs.rb
- config/routes.rb
mypage配下に本人確認ページを作成
ルーティング設定
コントローラーの設定
本人確認ページの見た目を作成するため
> 【WIP】【マークアップ】ユーザー本人確認ページ

- app/views/devise/sessions/logout.html.haml
- app/views/mypage/_mypage-sidebar.html.haml
- config/breadcrumbs.rb
ログアウトページのパンくず追加
サイドバーナビのログアウトページリンク修正
ログアウトページ周りの修正
> ログアウトページ周りの修正

- app/assets/stylesheets/purchase/_purchase.scss
- app/controllers/purchase_controller.rb
- app/views/purchase/done.html.haml
- app/views/purchase/index.html.haml
画像をDBからとってくる
崩れてしまった商品購入画面のビュー修正
本家メルカリとほぼ同じ見た目にしたかったため
> 画像の読み込み　scss調整

- app/assets/stylesheets/modules/_products_detail.scss
- app/views/shared/_products_page_detail.html.haml
サーバサイドの調整
複数枚投稿の画像表示修正
商品詳細ページの最終調整
> 商品詳細ページの調整

- app/controllers/products_controller.rb
- db/migrate/20191229044350_create_products.rb
- db/schema.rb
why
商品出品機能の実装のため
what
商品出品機能が必要だから
> 【サーバサイド】商品出品2

- app/controllers/mypage_controller.rb
- app/views/mypage/profile.html.haml
- db/schema.rb
プロフィール画像をでデフォルト画像に設定する
current_userのnameカラムをニックネームとして表示する
本家メルカリに近づけるため
> プロフィール編集画面の修正

- app/controllers/products_controller.rb
- app/controllers/purchase_controller.rb
- app/models/product.rb
- app/views/purchase/done.html.haml
- app/views/purchase/index.html.haml
- config/routes.rb
- db/migrate/20191229044350_create_products.rb
- db/schema.rb
商品詳細表示のサーバーサイドの修正
詳細を確認できるようにするため
> サーバーサイド　修正

- app/assets/javascripts/category_form.js
- app/assets/stylesheets/modules/_new_product.scss
- app/views/products/_form.html.haml
- app/views/products/new.html.haml
出品ページのビューを整えます
サーバサイド実装後にビューが崩れたため
> 【フロント】商品出品ページのビュー崩れ修正

- app/assets/javascripts/products.js
- app/assets/stylesheets/modules/_new_product.scss
- app/views/products/_form.html.haml
商品出品ページのjs,haml,scssファイルを修正する
#Why
複数枚投稿ページのビュー崩れ修正
> 複数枚画像投稿ページ修正

- app/assets/stylesheets/modules/_new_product.scss
- app/views/products/_form.html.haml
- app/views/products/edit.html.haml
- app/views/shared/_products_page_detail.html.haml
・カテゴリとブランドを出品時データを反映する
・カテゴリは大カテゴリのみを表示する
・一部「必須」を「任意」にする
詳細画面の調整をするため
> 商品詳細ページの修正

- app/controllers/products_controller.rb
- app/views/products/edit.html.haml
why
編集画面でエラーが起きていたのでその対応のため
what
エラー画面が出ると大変だから
> 【サーバサイド】商品情報編集2

- app/views/shared/_products_page_detail.html.haml
why
今のままだと編集ボタンが押せないため
what
編集がするため
> 編集に飛ぶためのパス指定

- app/views/shared/_products_page_detail.html.haml
・商品詳細ページに条件分岐文を追記する
出品者自身が購入できないようにする
> 出品者自身が購入ボタンを押せる状態を修正する

- app/controllers/products_controller.rb
- app/controllers/purchase_controller.rb
- app/views/devise/registrations/new.html.haml
- app/views/devise/registrations/new_address.html.haml
- app/views/mypage/identification.html.haml
- app/views/mypage/profile.html.haml
productsコントローラーindexアクション
purchaseコントローラーpayアクション
を編集
ビューファイル微修正
購入された商品がトップページに表示されないようにするため。
> ビューを微修正、購入された商品が表示されないようにする。

- README.md
- app/models/brand.rb
- app/models/size.rb
- db/migrate/20200110053511_create_sizes.rb
- db/migrate/20200110060547_create_brands.rb
- db/schema.rb
- spec/factories/brands.rb
- spec/factories/sizes.rb
- spec/models/brand_spec.rb
- spec/models/size_spec.rb
why
使わないファイルだから
what
使わなくなったテーブルのがあるのでその削除
> 使わなくなったモデルの削除

- app/models/product.rb
why
商品出品をして、入れ忘れをするとエラーが出るため
what
エラー画面を出さなくするため
> バリテーションの追加
